### ISSUE TITLE
Broken html page 

### ISSUE THREAD

**Issue by pamjesus** [RotorHazard/RotorHazard#182]
The web page at _/database_ address is broken.

At the Browser, head of the page
=
jinja2.exceptions.UndefinedError
UndefinedError: 'savedraces' is undefined
...

At the Console
===================
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/pnmfonseca/RotorHazard/src/server/server.py", line 599, in decorated
    return f(*args, **kwargs)
  File "/home/pi/pnmfonseca/RotorHazard/src/server/server.py", line 681, in database
    globalSettings=GlobalSettings)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/pnmfonseca/RotorHazard/src/server/templates/database.html", line 1, in top-level template code
    {% extends "layout.html" %} {% block title %}Database{% endblock %} {% block content %}
  File "/home/pi/pnmfonseca/RotorHazard/src/server/templates/layout.html", line 94, in top-level template code
    {% block content %}{% endblock %}
  File "/home/pi/pnmfonseca/RotorHazard/src/server/templates/database.html", line 120, in block "content"
    {% for savedrace in savedraces.query.all() %}
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'savedraces' is undefined
Client disconnected

Problem Root cause
===================
File src/server/templates/database.html is refering the class model savedraces. This object looks, now, to be the savedraceLap.

**Comment by pamjesus** [comment]
Fortunately, it is an easy fix.

Please, consider the patch
[0001-Fix-bronken-page.zip](https://github.com/RotorHazard/RotorHazard/files/3827821/0001-Fix-bronken-page.zip)

**Comment by pulquero** [comment]
If you're able, please create a PR.

**Comment by pamjesus** [comment]
PR requires a target branch.  What's the best option, at this time.
