### ISSUE TITLE
Event page is non-functional (2.1.0 dev 3)

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#200]
Server errors when event page is viewed, so no event overview data is loaded.
Version: 2.1.0 (dev 3)
Server API: 24
Node API: 21

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 648, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 677, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 284, in _handler
    *args)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 698, in _handle_event
    ret = handler(*args)
  File "server.py", line 1059, in on_load_data
    emit_class_data(nobroadcast=True)
  File "server.py", line 2876, in emit_class_data
    has_race = SavedRaceMeta.query.filter_by(class_id=race_class.id).one_or_none()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2933, in one_or_none
    "Multiple rows were found for one_or_none()")
MultipleResultsFound: Multiple rows were found for one_or_none()
2020-01-08T15:10:21Z <Thread at 0x749ee1c8: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7580a550>>(<socketio.server.Server object at 0x7580a550>, 'f10c77010c4b4467bdc3a32eb36cec89', [u'load_data', {u'load_types': [u'all_languages', , '/', None)> failed with MultipleResultsFound
```

**Comment by ethomas997** [comment]
Fixed by https://github.com/RotorHazard/RotorHazard/commit/b1d0a42d83a70d8b0c59322e9df79f15621410be
