### ISSUE TITLE
Server should handle going from 4 nodes to 8

### ISSUE THREAD

**Issue by ethomas997** [RotorHazard/RotorHazard#34]
The server should handle the hardware going from 4 nodes to 8; currently it seems to crash, as per the log output below reported on FB.  In this reported case it may be because laps were saved with 4 nodes.
```
pi@raspberrypi:~/RotorHazard/src/delta5server $ python server.py
Configuration file imported
Language file imported
Node 1 found at address 8
Node 2 found at address 10
Node 3 found at address 12
Node 4 found at address 14
Node 5 found at address 16
Node 6 found at address 18
Node 7 found at address 20
Node 8 found at address 22
Node 1: API_level=10, Freq=5658, EnterAt=190, ExitAt=120
Node 2: API_level=10, Freq=5732, EnterAt=192, ExitAt=160
Node 3: API_level=10, Freq=5806, EnterAt=192, ExitAt=160
Node 4: API_level=10, Freq=5917, EnterAt=192, ExitAt=160
Node 5: API_level=10, Freq=5800, EnterAt=192, ExitAt=160
Node 6: API_level=10, Freq=5800, EnterAt=192, ExitAt=160
Node 7: API_level=10, Freq=5800, EnterAt=192, ExitAt=160
Node 8: API_level=10, Freq=5800, EnterAt=192, ExitAt=160
Number of nodes found: 8
Found installed: java version "1.8.0_65"
Found installed: IMDTabler Version 1.3
Traceback (most recent call last):
File "server.py", line 3005, in <module>
db_reset_current_laps()
File "server.py", line 2734, in db_reset_current_laps
DB.session.query(CurrentLap).delete()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3440, in delete
delete_op.exec_()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 1636, in exec_
self._do_exec()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 1866, in _do_exec
self._execute_stmt(delete_stmt)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 1642, in _execute_stmt
stmt, params=self.query._params, mapper=self.mapper
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1263, in execute
clause, params or {}
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 980, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
distilled_params,
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
e, statement, parameters, cursor, context
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
util.raise_from_cause(sqlalchemy_exception, exc_info)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
cursor, statement, parameters, context
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'DELETE FROM current_lap'] (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by HazardCreative** [comment]
Why would the server return "attempt to write a readonly database" at this instance?

**Comment by HazardCreative** [comment]
This should probably be expanded to "server should do more database consistency checks". For example, there should never be an empty Pilots or Heats table. If one is detected, data recovery should occur. This can happen if the user fails to install a dependency and tries to start up the server or the initialization is otherwise interrupted. An incomplete default database will cause the server to fail on next startup.

**Comment by HazardCreative** [comment]
After 95d7876, my code now tolerates a node number increase. However, I never saw the error above with "attempt to write a readonly database". Steps to reproduce the above?

**Comment by ethomas997** [comment]
Looks like the other mods have fixed this issue.
