### ISSUE TITLE
RotorHazard v4.2.0-beta.1 compatibility issue with FPV Trackside 2.0.59

### ISSUE THREAD

**Issue by jurgelenas** [RotorHazard/RotorHazard#948]
We encountered the following error when attempting to start a race using the latest RotorHazard v4.2.0-beta.1 and FPV Trackside 2.0.59. Unfortunately, this is all the information I currently have, but I may be able to provide a full SQLite dump later.

The issue did not occur at the beginning of the event. We successfully completed roughly half of the races without any problems. However, the error began to appear more frequently as we progressed, eventually preventing us from starting races altogether. Could be a race condition?

```
Sep 01 08:14:21 rotorhazard python3[4012]: Current laps cleared                                                                                                                                               
Sep 01 08:14:21 rotorhazard python3[4012]: Traceback (most recent call last):                                                                                                                                 
Sep 01 08:14:21 rotorhazard python3[4012]:   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run                                                                                
Sep 01 08:14:21 rotorhazard python3[4012]:   File "/usr/local/lib/python3.9/dist-packages/socketio/server.py", line 733, in _handle_event_internal                                                            
Sep 01 08:14:21 rotorhazard python3[4012]:     r = server._trigger_event(data[0], namespace, sid, *data[1:])                                                                                                  
Sep 01 08:14:21 rotorhazard python3[4012]:   File "/usr/local/lib/python3.9/dist-packages/socketio/server.py", line 758, in _trigger_event                                                                    
Sep 01 08:14:21 rotorhazard python3[4012]:     return self.handlers[namespace][event](*args)                                                                                                                  
Sep 01 08:14:21 rotorhazard python3[4012]:   File "/usr/local/lib/python3.9/dist-packages/flask_socketio/__init__.py", line 282, in _handler                                                                  
Sep 01 08:14:21 rotorhazard python3[4012]:     return self._handle_event(handler, message, namespace, sid,                                                                                                    
Sep 01 08:14:21 rotorhazard python3[4012]:   File "/usr/local/lib/python3.9/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event                                                             
Sep 01 08:14:21 rotorhazard python3[4012]:     ret = handler(*args)                                                                                                                                           
Sep 01 08:14:21 rotorhazard python3[4012]:   File "/opt/RotorHazard/src/server/plugins/rh_connector_trackside/__init__.py", line 66, in race_stage                                                            
Sep 01 08:14:21 rotorhazard python3[4012]:     self._rhapi.db.heat_alter(heat.id, name="TrackSide Heat {}".format(heat.id))                                                                                   
Sep 01 08:14:21 rotorhazard python3[4012]:   File "/opt/RotorHazard/src/server/RHAPI.py", line 53, in wrapper                                                                                                 
Sep 01 08:14:21 rotorhazard python3[4012]:     return func(self, *args, **kwargs)                                                                                                                             
Sep 01 08:14:21 rotorhazard python3[4012]:   File "/opt/RotorHazard/src/server/RHAPI.py", line 373, in heat_alter                                                                                             
Sep 01 08:14:21 rotorhazard python3[4012]:     return self._racecontext.rhdata.alter_heat(data)
Sep 01 08:14:21 rotorhazard python3[4012]:   File "/opt/RotorHazard/src/server/RHData.py", line 1196, in alter_heat
Sep 01 08:14:21 rotorhazard python3[4012]:     event_results = json.loads(self.get_option("eventResults"))
Sep 01 08:14:21 rotorhazard python3[4012]:   File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
Sep 01 08:14:21 rotorhazard python3[4012]:     raise TypeError(f'the JSON object must be str, bytes or bytearray, '
Sep 01 08:14:21 rotorhazard python3[4012]: TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Sep 01 08:14:21 rotorhazard python3[4012]: 2024-09-01T07:14:21Z <Thread at 0x735717a8: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x747b3b38>>(<socketio.server.Server object at 0x747b3b38>, 'MnwG0TTpfvitCZvmAAAY', 'WNb0gLcB8i_Si1mUAAAX', ['ts_race_stage', {'start_time_s': 1686.5780041, ', '/', 22)> failed with TypeError
Sep 01 08:14:21 rotorhazard python3[4012]: Heat added: Heat 1
```

**Comment by HazardCreative** [comment]
Please update us on this issue. Does it continue to occur with beta.2? If so, please provide the debug log dump for debugging so that we can investigate. Thank you!

**Comment by HazardCreative** [comment]
Closing since a code change was made that should prevent it, and no further activity has occurred.
