### ISSUE TITLE
reqsNonPi.txt and cffi==1.15.*

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#961]
Whenever using vscode to run rotorhazard for plugin development I find I have to comment out cffi==1.15.* in reqsNonPi.txt to get it all to install correctly. Rotorhaxard seems to run fine without it. Does this need to be in the reqsNonPi.txt file?

**Comment by HazardCreative** [comment]
It's best practice to define the full set of requirements, so let's instead determine what it is about this that's problematic. What else can you tell us about your environment? The error you're getting? Python version? List of your installed packages?

**Comment by Aaronsss** [comment]
Python 3.12.7

```powershell
Collecting cffi==1.15.* (from -r .\reqsNonPi.txt (line 21))
  Using cached cffi-1.15.1.tar.gz (508 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "C:\Users\aaron\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\aaron\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main   
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\aaron\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-q4p3tqo4\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-q4p3tqo4\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-q4p3tqo4\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-q4p3tqo4\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 126, in <module>
        File "<string>", line 105, in uses_msvc
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-q4p3tqo4\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 220, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-q4p3tqo4\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 132, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-q4p3tqo4\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 379, in compile
          self.initialize()
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-q4p3tqo4\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 289, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-q4p3tqo4\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 150, in _get_vc_env
          raise DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
``` 

```powershell
Package            Version
------------------ --------
Adafruit_GPIO      1.0.3
Adafruit-PureIO    1.1.11
asyncio            3.4.3
asyncio-gevent     0.2.5
bidict             0.22.1
blinker            1.7.0
certifi            2024.2.2
cffi               1.17.1
charset-normalizer 3.3.2
click              8.1.7
colorama           0.4.6
Flask              3.0.2
Flask-SocketIO     5.3.6
Flask-SQLAlchemy   2.4.4
gevent             23.9.1
gevent-websocket   0.10.1
greenlet           3.0.3
idna               3.6
itsdangerous       2.1.2
Jinja2             3.1.3
MarkupSafe         2.1.5
mock               5.1.0
pi-ina219          1.4.1
pip                24.0
pycparser          2.21
pyserial           3.4
python-engineio    4.4.1
python-socketio    5.8.0
pytz               2024.1
requests           2.32.3
RPi.bme280         0.2.4
setuptools         69.0.3
simpleobsws        1.3.1
smbus2             0.4.3
SQLAlchemy         2.0.28
typing_extensions  4.9.0
urllib3            2.2.0
websocket-client   1.5.3
websockets         12.0
Werkzeug           3.0.1
zope.event         5.0
zope.interface     6.1
``` 

Seems pip install cffi works but pip install cffi==1.15.0 does not

Tried installing the suggested build tools without much success

**Comment by HazardCreative** [comment]
So you do have `cffi`, it's just a newer version. Perhaps we can simply update the dependency requirement here.

**Comment by ethomas997** [comment]
Yeah, it looks like the 'cffi' library added support for Python after v1.15.x.  The current version, 1.17.x, is still compatible with Python 3.8, so we'll update our reqs to that.

**Comment by ethomas997** [comment]
Fixed via commit https://github.com/RotorHazard/RotorHazard/commit/e38bb6ef96a1b472edf5b9114f41018f35632afb
